language: objective-c
osx_image: xcode12.2
xcode_project: PowerMate Control Center.xcodeproj
xcode_scheme: PowerMate Control Center
xcode_destination: platform=macOS
script:
- set -o pipefail
- xcodebuild -project PowerMate\ Control\ Center.xcodeproj -scheme PowerMate\ Control\ Center -destination platform\=macOS build | xcpretty
